version: '2'

services:

  bulker:
    image: idobry/bulker:0.0.0
    environment:
      - REDIS_HOST=redis:6380
    ports:
      - '6379:6379'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'
    #volumes:
    #  - /path/to/redis-persistence:/bitnami/redis/data